### ISSUE TITLE
Error running irap_install.sh

### ISSUE THREAD

**Issue by Niklas123Niklas** [nunofonseca/irap#19]
Hi there,
I tried to install iRAP on my Ubuntu 14.04 system, but it fails and I cannot solve the Problem. Can you help me? I attach the .log file. If you need more information, please ask for them.
Niklas

[log.txt](https://github.com/nunofonseca/irap/files/669216/log.txt)

**Comment by nunofonseca** [comment]
Dear Niklas,

Thanks for the log file. It seems that mono failed to compile. This may be due to some  library not being installed. A list of all dependencies (for Ubuntu) that should be installed  is available here: https://github.com/nunofonseca/irap/blob/master/docker/install_tests/ubuntu_latest.docker.  Therefore a solution involves installing any missing dependencies  and then restart the installation.
If the problem persists then please install iRAP step by step (https://github.com/nunofonseca/irap/wiki/2---How-to-install-and-update-iRAP#manual-install--option-2).

Cheers.

**Comment by Niklas123Niklas** [comment]
Hey,

I installed all dependencies as mentioned. The Error still occures. With manual installation the error message happens during step 6. 
I attached the new logfile, but it is the same error message as before. 

[2912161226.txt](https://github.com/nunofonseca/irap/files/676993/2912161226.txt)
Niklas

**Comment by nunofonseca** [comment]
Hi, 
Indeed, mono compilation is still failing.  Unfortunately I can't  determine what is the problem and I'm unable to reproduce it in Ubuntu.  Therefore I suggest that you report the issue to the mono community (http://www.mono-project.com/community/), hopefully they will know how to solve it.

Note that Mono is only required by Fusionmap and  OSA.  If you don't plan to use these tools then you may skip their installation.  In this case, just ignore the error and proceed to the next installation steps to complete the installation.

Once iRAP is installed, you may install STAR  by running the following command in the cloned iRAP folder
irap_install.sh -s . -x star

Cheers.

**Comment by Niklas123Niklas** [comment]
Hey,
I did it without mono and it worked. Due to resource limitations I had to swap to an other computer with Ubuntu 12.04 running, there it worked without problems.
Thanks for the help.

**Comment by nunofonseca** [comment]
Great!
