### ISSUE TITLE
more guideline for Atlas SOP

### ISSUE THREAD

**Issue by wangyugui** [nunofonseca/irap#35]
Hi @nunofonseca 

We need more guideline for Atlas SOP to get the same result like Expression Atlas.

Result sample:
https://www.ebi.ac.uk/gxa/experiments/E-MTAB-2690/Downloads

Question1:
How to get both TPM and FPKM Expression values across all genes?
"sop=atlas" does not work as expected.

Question2:
Can we run iRAP without DE when we get these TPM and FPKM Expression values ?

I used the version irap-v0.8.5p4 but failed to the right way to do these.

Best Regards

**Comment by nunofonseca** [comment]
Hi,

Question1:
a) For details on how data is generated for Expression Atlas (per assay/sample) please take a look at https://doi.org/10.1093/bioinformatics/btx143 (there is a file with the commands).
b) if you use irap (instead of irap_single_lib) then to get TPM and FPKM you will have to run irap twice (the second time it will only compute the TPM or FPKM, whatever is missing). Something like:
irap conf=your_conf_file.conf sop=atlas quant_norm_method=fpkm
irap conf=your_conf_file.conf sop=atlas quant_norm_method=tpm
c) if you still don' t get the results that you expect, then please give an example of what you would expect versus what you get.

Regarding question 2:
To disable DE analysis set de_method=none in your .conf file.

Cheers.

**Comment by wangyugui** [comment]
'irap_single_lib' works well.

and it seems that fpkms/TPM is generated by iRAP/DEXSeq.
